version: "3"

services:
    mongo:
        image: mongo:latest
        ports:
            - "27017:27017"
    bored-api:
        image: bored-api:1.0.0
        environment:
            - NODE_ENV=production
            - MONGODB_URI=mongodb://mongo:27017/boredapi
            - PORT=5000
        ports:
            - "5000:5000"
        depends_on:
            - mongo
